name: Build
on: push

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build exiftool-dll
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          cmake --install build --prefix install
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: exiftool-dll-macos
          path: install

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build exiftool-dll
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          cmake --install build --prefix install
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: exiftool-dll-windows
          path: install
